#!/bin/zsh

antigen use oh-my-zsh

(( $+commands[git] )) && antigen bundle git
antigen bundle history
(( $+commands[emacs] )) && antigen bundle emacs
(( $+commands[colorize] )) && antigen bundle colorize
antigen bundle extract
antigen bundle man
(( $+commands[tmux] )) && antigen bundle tmux
(( $+commands[rg] )) && antigen bundle ripgrep
antigen bundle colored-man-pages
(( $+commands[tig] )) && antigen bundle tig
(( $+commands[go] )) && antigen bundle golang
(( $+commands[pip] )) && antigen bundle pip
antigen bundle jira
(( $+commands[rustup] )) && antigen bundle rustup
(( $+commands[rustc] )) && antigen bundle rust
(( $+commands[cargo] )) && antigen bundle cargo
(( $+commands[code] )) && antigen bundle vscode
(( $+commands[fuck] )) && antigen bundle thefuck

antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-completions

case "$OSTYPE" in
    darwin*)
        antigen bundle osx
        (( $+commands[brew] )) && antigen bundle brew
        antigen bundle gnu-utils
        ;;
    linux*)
        (( $+commands[lsb_release] )) && [[ $(lsb_release -is) == "Ubuntu" ]] && antigen bundle ubuntu
        (( $+commands[systemctl] )) && antigen bundle systemd
esac

antigen theme ssegal/zsh-theme@stuff

[[ -e $HOME/.antigenrc.local ]] && source $HOME/.antigenrc.local

antigen apply
