#!/bin/zsh

antigen use oh-my-zsh

antigen bundle colored-man-pages
(( $+commands[colorize] )) && antigen bundle colorize
(( $+commands[docker] )) && antigen bundle docker
(( $+commands[emacs] )) && antigen bundle emacs
antigen bundle extract
(( $+commands[git] )) && antigen bundle git
(( $+commands[go] )) && antigen bundle golang
antigen bundle history 
antigen bundle man
(( $+commands[pip] )) && antigen bundle pip
(( $+commands[rg] )) && antigen bundle ripgrep
(( $+commands[rustc] )) && antigen bundle rust
(( $+commands[ssh-agent] )) && antigen bundle ssh-agent
(( $+commands[thefuck] )) && antigen bundle thefuck
(( $+commands[tmux] )) && antigen bundle tmux
(( $+commands[code] )) && antigen bundle vscode

antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-history-substring-search
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-completions

case "$OSTYPE" in
    darwin*)
        antigen bundle macos
        (( $+commands[brew] )) && antigen bundle brew
        antigen bundle gnu-utils
        ;;
    linux*)
        (( $+commands[lsb_release] )) && [[ $(lsb_release -is) == "Ubuntu" ]] && antigen bundle ubuntu
        (( $+commands[systemctl] )) && antigen bundle systemd
esac

antigen theme ssegal/zsh-theme@stuff

[[ -e $HOME/.antigenrc.local ]] && source $HOME/.antigenrc.local

antigen apply
