FROM alpine:3.19

RUN apk --no-interactive update && apk --no-interactive add curl zsh sudo git
RUN adduser -Ds /bin/ash testuser
RUN echo "testuser  ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

USER testuser
WORKDIR /home/testuser
RUN mkdir -p /home/testuser/.dotfiles

CMD /bin/ash
