# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Don't add a blank line between shell prompts
add_newline = false

[aws]
symbol = "  "

[buf]
symbol = " "
disabled = true

[c]
symbol = " "
disabled = true

[conda]
symbol = " "
disabled = true

[crystal]
symbol = " "
disabled = true

[dart]
symbol = " "
disabled = true

[directory]
read_only = " 󰌾"

[docker_context]
symbol = " "

[elixir]
symbol = " "
disabled = true

[elm]
symbol = " "
disabled = true

[fennel]
symbol = " "
disabled = true

[fossil_branch]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "
disabled = true

[guix_shell]
symbol = " "
disabled = true

[haskell]
symbol = " "
disabled = true

[haxe]
symbol = " "
disabled = true

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "
disabled = true

[julia]
symbol = " "
disabled = true

[kotlin]
symbol = " "
disabled = true

[lua]
symbol = " "
disabled = true

[memory_usage]
symbol = "󰍛 "
disabled = true

[meson]
symbol = "󰔷 "
disabled = true

[nim]
symbol = "󰆥 "
disabled = true

[nix_shell]
symbol = " "
disabled = true

[nodejs]
symbol = " "
disabled = true

[ocaml]
symbol = " "
disabled = true

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "
disabled = true

[perl]
symbol = " "
disabled = true

[php]
symbol = " "
disabled = true

[pijul_channel]
symbol = " "
disabled = true

[python]
symbol = " "
disabled = true

[rlang]
symbol = "󰟔 "
disabled = true

[ruby]
symbol = " "
disabled = true

[rust]
symbol = " "
disabled = true

[scala]
symbol = " "
disabled = true

[swift]
symbol = " "
disabled = true

[zig]
symbol = " "
disabled = true
