#cloud-config

# Configuration for Ubuntu 20.04 (focal)

users:
  - name: ssegal
    groups: sudo
    gecos: Stephen Segal
    shell: /bin/zsh
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    ssh_import_id: gh:ssegal
apt:
  preserve_sources_list: true
  sources:
    ignored1:
      source: "ppa:kelleyk/emacs"
    ignored2:
      source: "ppa:git-core/ppa"
package_upgrade: true
timezone: "America/New_York"
disable_root: true
packages:
  - zsh
  - build-essential
  - git
  - emacs27-nox
  - tmux
  - colorize
  - ripgrep
runcmd:
  - curl -L https://raw.githubusercontent.com/ssegal/dotfiles/stuff/cloud-init/home-provision.sh | sudo --set-home --non-interactive --user=ssegal /bin/bash
package_reboot_if_required: true
