#cloud-config

# Configuration for Ubuntu 22.04 (jammy)

users:
  - name: ssegal
    groups: [dialout, cdrom, floppy, audio, video, plugdev, users, sudo, docker]
    gecos: Stephen Segal
    shell: /bin/zsh
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    ssh_import_id: gh:ssegal
apt:
  preserve_sources_list: true
  sources:
    ignored1:
      source: "ppa:ubuntuhandbook1/emacs"
    ignored2:
      source: "ppa:git-core/ppa"
    docker.list:
      source: deb https://download.docker.com/linux/ubuntu $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

package_upgrade: true
package_update: true
timezone: "America/New_York"
disable_root: true
packages:
  - zsh
  - build-essential
  - git
  - emacs-nox
  - tmux
  - colorize
  - ripgrep
  - pkg-config
  - procps
  - curl
  - file
  - git
  - docker-ce
  - docker-ce-cli
runcmd:
  - curl -L https://raw.githubusercontent.com/ssegal/dotfiles/stuff/cloud-init/home-provision.sh | sudo --set-home --non-interactive --user=ssegal /bin/bash
package_reboot_if_required: true
