#!/bin/false
# -*- mode: sh; sh-shell: zsh; -*-

typeset -U path PATH
typeset -U pkg_config_path PKG_CONFIG_PATH

SCRIPT_DIR=${${(%):-%x}:a:h}

source ${SCRIPT_DIR}/antidote/antidote.zsh
antidote load

(( $+commands[starship] )) && eval "$(starship init zsh)"

if [[ -n ${HOMEBREW_PREFIX:-} ]] && [[ $OSTYPE == darwin* ]]; then
    for bindir in "${HOMEBREW_PREFIX}/opt/"*"/libexec/gnubin"; do path=($bindir $path); done
fi

[[ -n ${HOMEBREW_PREFIX:-} ]] && export PKG_CONFIG_PATH="${HOMEBREW_PREFIX}/lib/pkgconfig"${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}
[[ -d ${HOME}/.local/lib/pkgconfig ]] && export PKG_CONFIG_PATH=" ${HOME}/.local/lib/pkgconfig"${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}

export ALTERNATE_EDITOR=
(( $+commands[emacsclient] )) && export EDITOR='emacsclient -t'
(( $+commands[edit] )) && export EDITOR="edit"
(( $+commands[zoxide] )) && eval "$(zoxide init zsh)"
(( $+commands[fzf] )) && eval "$(fzf --zsh)"
(( $+commands[python3] )) && path+="$(python3 -m site --user-base)/bin"
(( $+commands[go] )) && path+="$(go env GOPATH)/bin"
(( $+commands[dircolors] )) && eval "$(dircolors -b)"

(( $+commands[lesspipe.sh] )) && eval "$(lesspipe.sh)"
export LESS=' -R '

if (( $+commands[eza] )); then
    alias ls="eza"
    alias ll="eza -l --icons --git"
    alias lt="eza --tree"
fi

if (( $+commands[bat] )); then
    export LESSCOLORIZER="bat -p --theme=DarkPlus"
    export MANPAGER="sh -c 'col -bx | bat -l man -p'"
    export MANROFFOPT="-c"
elif (( $+commands[batcat] )); then
    export LESSCOLORIZER="batcat -p --theme=DarkPlus"
    export MANPAGER="sh -c 'col -bx | batcat -l man -p'"
    export MANROFFOPT="-c"
fi

if (( $+commands[thefuck] )); then
    eval "$(thefuck --alias)"
fi

if (( $+commands[emacsclient] )); then
    alias te="emacsclient -t"
    alias ec="emacsclient"
fi

export EMAIL="ssegal127@gmail.com"
export TZ="America/New_York"

# Clear any error state
true
