#!/bin/false
# -*- mode: sh; sh-shell: zsh; -*-

typeset -U path PATH
typeset -U pkg_config_path PKG_CONFIG_PATH

SCRIPT_DIR=${${(%):-%x}:a:h}

source ${SCRIPT_DIR}/antidote/antidote.zsh
antidote load

(( $+commands[starship] )) && source <(starship init zsh)

if [[ -n ${HOMEBREW_PREFIX:-} ]] && [[ $OSTYPE == darwin* ]]; then
    for bindir in "${HOMEBREW_PREFIX}/opt/"*"/libexec/gnubin"; do path=($bindir $path); done
fi

[[ -n ${HOMEBREW_PREFIX:-} ]] && export PKG_CONFIG_PATH="${HOMEBREW_PREFIX}/lib/pkgconfig"${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}
[[ -d ${HOME}/.local/lib/pkgconfig ]] && export PKG_CONFIG_PATH=" ${HOME}/.local/lib/pkgconfig"${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}

[[ -r ${HOME}/.cargo/env ]] && source ${HOME}/.cargo/env

export ALTERNATE_EDITOR=
(( $+commands[emacsclient] )) && export EDITOR='emacsclient -t'
(( $+commands[edit] )) && export EDITOR="edit"
(( $+commands[zoxide] )) && source <(zoxide init zsh)
(( $+commands[fzf] )) && source <(fzf --zsh)
(( $+commands[python3] )) && path+="$(python3 -m site --user-base)/bin"
(( $+commands[go] )) && path+="$(go env GOPATH)/bin"
(( $+commands[dircolors] )) && source <(dircolors -b)
(( $+commands[brew] )) && export HOMEBREW_NO_UPGRADE_AUTO_UPDATES_CASKS=1

(( $+commands[lesspipe.sh] )) && source <(lesspipe.sh)
export LESS=' -R '
export VISUAL="$EDITOR"

if (( $+commands[eza] )); then
    alias ls="eza"
    alias ll="eza -l --icons --git"
    alias lt="eza --tree"
fi

if (( $+commands[bat] )); then
    export LESSCOLORIZER="bat -p"
    export MANPAGER="sh -c 'col -bx | bat -l man -p'"
    export MANROFFOPT="-c"
elif (( $+commands[batcat] )); then
    export LESSCOLORIZER="batcat -p"
    export MANPAGER="sh -c 'col -bx | batcat -l man -p'"
    export MANROFFOPT="-c"
fi

(( $+commands[thefuck] )) && source <(thefuck --alias)

e() {
    if [[ $INSIDE_EMACS == "ghostel" ]]; then
        ghostel_cmd find-file-other-window "$@"
    else
        $EDITOR "$@"
    fi
}

export EMAIL="ssegal127@gmail.com"
export TZ="America/New_York"

# Set up agent forwarding in WSL
if (( $+commands[wslinfo] &&
      $+commands[npiperelay.exe] &&
      $+commands[socat] )) &&
   [[ -z $SSH_AUTH_SOCK ]]; then
    # Set up agent forwarding
    export SSH_AUTH_SOCK=$HOME/.ssh/agent/windows.sock
    if [ ! -S $SSH_AUTH_SOCK ]; then
        mkdir -pm 700 ~/.ssh/agent
        socat UNIX-LISTEN:$SSH_AUTH_SOCK,fork EXEC:"npiperelay.exe -ei -s //./pipe/openssh-ssh-agent",nofork &
    fi
fi

# Clear any error state
true
