# -*- mode: sh; sh-shell: bash -*-
# shellcheck shell=bash

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)

# shellcheck disable=SC1091
source "${SCRIPT_DIR}/lib/utils.bash"

if [[ -x /usr/local/bin/brew ]]; then
    eval "$(/usr/local/bin/brew shellenv bash)"
elif [[ -x /opt/homebrew/bin/brew ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv bash)"
elif [[ -x /home/linuxbrew/.linuxbrew/bin/brew ]]; then
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv bash)"
fi

if [[ -n ${HOMEBREW_PREFIX:-} ]] && [[ $OSTYPE == darwin* ]]; then
    for bindir in "${HOMEBREW_PREFIX}/opt/"*"/libexec/gnubin"; do export PATH="$bindir":$PATH; done
    for mandir in "${HOMEBREW_PREFIX}/opt/"*"/libexec/gnuman"; do export MANPATH="$mandir":$MANPATH; done
fi

[[ -d $HOME/.local/share/man ]] && export MANPATH="$HOME/.local/share/man":$MANPATH
# shellcheck disable=SC1091
source_if_exists "$HOME/.cargo/env"

# This should be the last item prepended to the PATH because it should always be
# searched first.
[[ -d $HOME/.local/bin ]] && export PATH="$HOME/.local/bin":$PATH

command_exists python3 && PATH=$PATH:"$(python3 -m site --user-base)/bin"
command_exists go && PATH=$PATH:$(go env GOPATH)/bin

export EMAIL="ssegal127@gmail.com"

[[ -n ${HOMEBREW_PREFIX:-} ]] && export PKG_CONFIG_PATH="${HOMEBREW_PREFIX}/lib/pkgconfig"${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}
[[ -d ${HOME}/.local/lib/pkgconfig ]] && export PKG_CONFIG_PATH=" ${HOME}/.local/lib/pkgconfig"${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}

export ALTERNATE_EDITOR=
command_exists emacsclient && export EDITOR='emacsclient -t'
command_exists edit && export EDITOR="edit"

export TZ=America/New_York

command_exists batpipe && eval "$(batpipe)"

dedup_path_var PATH
if [[ -n $MANPATH ]]; then
    dedup_path_var MANPATH
    # End MANPATH with a colon so the default manpath is appended.
    export MANPATH=$MANPATH:
fi
dedup_path_var PKG_CONFIG_PATH

source_if_exists "${HOMEBREW_PREFIX}/share/bash-completion/bash_completion"
command_exists dircolors && eval "$(dircolors -b)"

# Clear any error state
true
