# shellcheck shell=bash

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)

# shellcheck disable=SC1091
source "${SCRIPT_DIR}/lib/utils.bash"

if [[ -x /usr/local/bin/brew ]]; then
    HOMEBREW_PREFIX="$(/usr/local/bin/brew --prefix)"
elif [[ -x /opt/homebrew/bin/brew ]]; then
    HOMEBREW_PREFIX="$(/opt/homebrew/bin/brew --prefix)"
elif [[ -x /home/linuxbrew/.linuxbrew/bin/brew ]]; then
    HOMEBREW_PREFIX="$(/home/linuxbrew/.linuxbrew/bin/brew --prefix)"
fi

if [[ $OSTYPE == darwin* ]]; then
    for bindir in "${HOMEBREW_PREFIX}/opt/"*"/libexec/gnubin"; do PATH="$bindir":$PATH; done
    for mandir in "${HOMEBREW_PREFIX}/opt/"*"/libexec/gnuman"; do MANPATH="$mandir":$MANPATH; done
fi

[[ -d ${HOMEBREW_PREFIX}/opt/man-db/libexec/bin ]]; PATH="${HOMEBREW_PREFIX}/opt/man-db/libexec/bin":$PATH
[[ -d ${HOMEBREW_PREFIX}/opt/man-db/libexec/man ]]; MANPATH="${HOMEBREW_PREFIX}/opt/man-db/libexec/man":$MANPATH
[[ -d $HOMEBREW_PREFIX ]] && PATH="$HOMEBREW_PREFIX/bin":"$HOMEBREW_PREFIX/sbin":$PATH
[[ -d $HOME/.local/bin ]] && PATH="$HOME/.local/bin":$PATH
[[ -d $HOME/.local/share/man ]] && MANPATH="$HOME/.local/share/man":$MANPATH
[[ -d $HOME/.cargo/bin ]] && PATH=$PATH:"$HOME/.cargo/bin"
command_exists python3 && PATH=$PATH:"$(python3 -m site --user-base)/bin"
command_exists go && PATH=$PATH:$(go env GOPATH)/bin


export PATH
export MANPATH
export EMAIL="ssegal127@gmail.com"

pkg_config_paths=(
    "$HOME/.local/lib/pkgconfig"
    "$HOMEBREW_PREFIX/pkgconfig"
    "/usr/local/lib/pkgconfig"
    "/lib/pkgconfig"
    "/lib/x86_64-linux-gnu/pkgconfig"
    "/usr/lib/pkgconfig"
    "/usr/lib/x86_64-linux-gnu/pkgconfig"
)

pkg_config_path=()
declare -A seen=()
for i in "${pkg_config_paths[@]}"; do
    if [[ -d $i && -z ${seen[$i]} ]]; then
        pkg_config_path+=("$i")
        seen[$i]=1
    fi
done

PKG_CONFIG_PATH=$(IFS=:; echo "${pkg_config_path[*]}")
export PKG_CONFIG_PATH
export ALTERNATE_EDITOR=
command_exists emacsclient && export EDITOR='emacsclient -t'
command_exists edit && export EDITOR="edit"

export TZ=America/New_York

if command_exists batpipe; then
    LESSOPEN="|$(command -v batpipe) -p %s"; export LESSOPEN
    export LESS="$LESS -R"
    export BATPIPE="color"
fi

dedup_path_var PATH
dedup_path_var MANPATH

command_exists dircolors && eval "$(dircolors -b)"

# Clear any error state
true
